### PR TITLE
Add new flavours of atoms

### PR DESCRIPTION
**Pull request by regiskuckaertz**
New atoms [are coming](https://github.com/guardian/content-atom/pull/88), I'm just setting up everything so I can work in atom-workshop locally.

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
👍 (once build is fixed)

**Comment by regiskuckaertz** [comment]
for some reason the build is timing out 😨

**Comment by marialivia16** [comment]
It looks good to me, it's very strange that the compilation is hanging forever. It happened before, but in this case I can't see why it fails. 

I tried to add the formats one by one and it worked up until the last one. Is there a limitation on the number of cases in a match? I'll have a closer look tomorrow 😃

**Comment by LATaylor-guardian** [comment]
@marialivia16 There used to be a limit on the number of cases in a match but I believe that was fixed so that does seem suspicious.

**Comment by regiskuckaertz** [comment]
The `typer` phase is generating a lot of symbols, like, _a lot_. I don't know if that's expected: `parse: 1009 → typer: 1624005 → ... erasure: 2294314` and the AST ends up with 25159803 nodes after `cleanup`. It feels like a lot.

**Comment by philwills** [comment]
👍 I've been meaning to have a go at moving to a generating a shapeless `Product`/`Coproduct` for the Scrooge generated classes, so there's not a need to reinvent this for Circe/Scanamo/Avro and that might potentially alleviate some of these issues. Circe also has the distinction between full-auto and semi-auto derivation, which might be a good way to make some of these workarounds less cryptic.

**Comment by regiskuckaertz** [comment]
@philwills I've tried to write a generic derivation [here](https://github.com/guardian/atom-maker/pull/27/files#diff-d9934d2597299ba1098278eab876e6f6R15) but I'm stuck with a compilation issue I do not really understand. I don't know if that is the correct approach anyway, would appreciate your advice here 😃

**Comment by regiskuckaertz** [comment]
Thanks a zillion @philwills , @marialivia16 and @LATaylor-guardian for your help with this one. Not very proud of typing all that boilerplate but it cut the compilation time by an order of magnitude. I guess it will do for now.

**Comment by marialivia16** [comment]
Great work! Thank you for doing this. I'll have a look on Monday, this looks too much for a Friday afternoon 👀

**Pull request merged**
